### ISSUE TITLE
Add Bandit library

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#115]
## Description

Add [Bandit](https://bandit.readthedocs.io/en/latest/) or similar.

> Bandit is a tool designed to find common security issues in Python code. To do this, Bandit processes each file, builds an AST from it, and runs appropriate plugins against the AST nodes. Once Bandit has finished scanning all the files, it generates a report.

**Comment by vinigfer** [comment]
@camilamaia Could you assign this for me please?
Implemented on PR https://github.com/scanapi/scanapi/pull/219
