### ISSUE TITLE
Create ScanAPI Github Action

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#117]
## Description

Create a Github Action for ScanAPI to make integrations easier. We already have a [docker image](https://github.com/scanapi/scanapi/blob/master/Dockerfile#L3) for it.

https://help.github.com/en/actions/building-actions/creating-a-docker-container-action

With this action we want to:

- Be able to use `scanapi` commands with args and options. i.e: `scanapi api.yaml`, `scanapi --help`, `scanapi api.yaml -c my_config_file.yaml` and so on.
- Be able to store the report as an artifact: https://github.com/actions/upload-artifact

We have already a repo for it: https://github.com/scanapi/github-action

**Comment by vinigfer** [comment]
By "report" you mean the for the examples, as mentioned on this issue: https://github.com/scanapi/scanapi/issues/153 ?

**Comment by camilamaia** [comment]
@vinigfer no sorry, I mean the html file generated by running scanapi command.

Let's suppose someone wants to use our github action. So he/she will want to run the command:

```
$ scanapi scanapi.yaml
```

and this command will generate a `scanapi-report.html`. This html is the one we call "report". 

I will improve the description of the other issue you commented about too, to make it more clear.

**Comment by camilamaia** [comment]
V1 is ready!

https://github.com/scanapi/github-action
https://github.com/marketplace/actions/scanapi
PR using it: https://github.com/scanapi/examples/pull/12

@barbosa @vinigfer I believe you guys will like it 😄
