### ISSUE TITLE
Bug: Extra lines on headers tables of Markdown Template

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#118]
## Description

Template is generating extra lines on headers tables of Markdown Template

## It is generating

| Header    | Value       |
|-----------|-------------|

| User-Agent | python-requests/2.23.0 |

| Accept-Encoding | gzip, deflate |

| Accept | */* |

| Connection | keep-alive |

| Content-Length | 2 |

| Content-Type | application/json |

## When it should generate

| Header    | Value       |
|-----------|-------------|
| User-Agent | python-requests/2.23.0 |
| Accept-Encoding | gzip, deflate |
| Accept | */* |
| Connection | keep-alive |
| Content-Length | 2 |
| Content-Type | application/json |

**Comment by barbosa** [comment]
@camilamaia this should do the trick:

https://jinja.palletsprojects.com/en/master/templates/#whitespace-control

**Comment by barbosa** [comment]
or maybe simply (need to double check):

```diff
- {% for key, value in request.headers.items() %}
- | {{ key }} | {{ value }} |
- {% endfor %}
+{% for key, value in request.headers.items() %}| {{ key }} | {{ value }} |{% endfor %}
```
