### ISSUE TITLE
Create ScanAPI spec from an OpenAPI specification

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#12]
## Create ScanAPI spec from an OpenAPI specification

Create a command that converts an OpenAPI specification file into a ScanAPI specification file.
OpenAPI Specification: https://swagger.io/specification/

For that, we need to create a new [Click](https://click.palletsprojects.com/en/7.x/) command called `convert` in the [`__main__.py`](https://github.com/scanapi/scanapi/blob/master/scanapi/__main__.py) file.

With the arguments:
- input file path (required)
- output file path (required)

And with the options:
- -f, --from, input_format. (default should be `openapi`, required)
- -t, --to, output_format. (default should be `scanapi`, required)

Example:
```
$ scanapi convert -f openapi -t scanapi OPENAPI_PATH SCANAPI_PATH 
```

Related issue: [ADR 6: How to integrate feature that converts OpenAPI file to ScanAPI file](https://github.com/scanapi/scanapi/issues/202)

**Comment by abreumatheus** [comment]
I started working on this. The main script is already done and working, i just need to integrate it into the main project and learn how to use Click to expose the CLI command.

You can check the current script [HERE](https://gist.github.com/abreumatheus/e10b13aea5747c959cb43cbe60917c21) .
Will be writing the tests and updating.

**Comment by camilamaia** [comment]
@abreumatheus wow, this was super fast! Let me test it! Thanks for the effort!

About the integration part, I've created an Architecture Decision Review (ADR) ticket to discuss it: https://github.com/scanapi/scanapi/issues/202. It would be awesome to hear your thoughts about it 🙂

**Comment by camilamaia** [comment]
I updated the ticket description according the decision made on [ADR 6: How to integrate feature that converts OpenAPI file to ScanAPI file](https://github.com/scanapi/scanapi/issues/202)

**Comment by abreumatheus** [comment]
> I updated the ticket description according to the decision made on [ADR 6: How to integrate feature that converts OpenAPI file to ScanAPI file](https://github.com/scanapi/scanapi/issues/202)

Created a PR on this at [#206 ] 😄

**Comment by camilamaia** [comment]
@abreumatheus i've created a specific issue to change the default command to `scanapi run` https://github.com/scanapi/scanapi/issues/226

This way we can start breaking this task in smaller ones.

**Comment by abreumatheus** [comment]
Hi guy, i'm back working on this. Was transitioning jobs and lacking time but now i'm able to pick up were i left. :)

**Comment by camilamaia** [comment]
Awesome @abreumatheus! Great news! I've reassigned you to the ticket 🚀

**Comment by abreumatheus** [comment]
@camilamaia A question came up here. Since the "params" key refers to query params, how do we work with path params?

**Comment by camilamaia** [comment]
@abreumatheus sorry for the huge delay. 

I will dedicate some time only for this ticket in the next months, since it is more complex. I will create a new repo only for it and probably a new plugin architecture, so people can implement their own converter. Like for Postman, Insomnia and so on...

Let me know if you'd like to join this journey haha

I will reassign the issue for me and block it for now, ok? If you'd like, I can add you also as an assignee :)
