### ISSUE TITLE
Add CLI options explanation

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#130]
## Description

To add explanations to each option. To tell the user what the option is for. Exactly how `help` has: `Show this message and exit.`

```bash
scanapi --help
Usage: scanapi [OPTIONS]

  Automated Testing and Documentation for your REST API.

Options:
  -s, --spec-path PATH
  -o, --output-path TEXT
  -c, --config-path TEXT
  -r, --reporter [console|markdown|html]
  -t, --template TEXT
  --log-level [DEBUG|INFO|WARNING|ERROR|CRITICAL]
  --help                          Show this message and exit.
```

Options:

- [ ] --spec-path
- [ ] --output-path
- [ ] --config-path
- [ ] --reporter
- [ ] --template
- [ ] --log-level

**Comment by barbosa** [comment]
I came to the issues list to add this very same issue when I saw you've already done it 🔮

**Comment by barbosa** [comment]
For reference: https://click.palletsprojects.com/en/7.x/documentation/#help-texts
