### ISSUE TITLE
Remove "inline" CSS from html report.

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#162]
Remove "inline" CSS from html report. Maybe using amazon s3 to store the stylesheets. We need to consider versioning.

**Comment by supakeen** [comment]
Is it that bad to have the CSS inline? Adding a 3rd party dependency for a locally generated report feels a bit weird especially if people say archive reports and they change? :)

**Comment by camilamaia** [comment]
Yeah, I believe I am good with inline CSS too. @djalmaaraujo what do you think of closing this issue?

**Comment by djalmaaraujo** [comment]
I would close it. I don't like the idea of calling external css too.
