### ISSUE TITLE
ADR 4: Remove Markdown Reporter

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#176]
## Architecture Decision Review - ADR

Based on the discussion we had in the #132, I have one suggestion. 

Suggestion:

- Remove markdown template for the main ScanAPI repository.
- Remove the flag "--reporter". Only html default report will be available.
- Create a new repo `scanapi/report-templates` and add markdown to it.
- In the `report-templates` we can manage to accept others templates from the community, the same vibe as danger plugins. Something like a reporter template marketplace.
- Of course, we will keep the `--template` flag. So the user will still be able to use custom templates.

Pros:
- We can remove all code that checks the reporter type.
- We don't have the "responsibility" to make markdown always super updated as we have for the `core` template of the project.
- We incentives others to create their own templates, since there is already one "external".
- We can make explain there, in this new repo, how to create new templates and how to use them.
- We don't have to worry **now for the first release** of how we will display the tests results in the markdown template (issues #164 #168 #170).
- We don't have to provide markdown examples at [scanapi-examples](https://github.com/scanapi/scanapi-examples)

Cons
- If we want to create new formats in the future (like to make integrations possible, for example), we would need to re add the logic that handles different formats.
- One core "feature" less for the user

@barbosa @gillianomenezes what do you think?

**Comment by barbosa** [comment]
@camilamaia I agree with taking it out and keeping HTML is the sole option. A markdown report could be generated without much effort by whoever is using the library.

About having a repo to store templates, I like the idea too. We just need to think a bit more about how this would be displayed. A simple list of files and folders in a GitHub repo won't be enough, I think.

Maybe we should define a structure that requires at least 3 things to consider it as valid template (thus a valid PR):
1. The Jinja template itself
2. A metadata file (yml/json containing name, description, author, tags, etc for the outstanding template)
3. A thumbnail in a specific format and size that could be displayed as showcase

We could also use Danger to validate these things BTW.

If all templates in this repo have these minimum requirements, in the future we could also have a tool to display and search for them in the website.

**Comment by camilamaia** [comment]
@barbosa I love the idea and I totally agree with it. 

Another option would be to let users have their jinja files in their own repos. We would need only a repo link instead of the jinja template itself. More or less like danger plugins.

But I would say I prefer your option. Just bringing another one to let us think...

**Comment by camilamaia** [comment]
@barbosa I've created a dedicated ADR to discuss it: https://github.com/scanapi/scanapi/issues/184
