### ISSUE TITLE
Status icons are not vertically centred in the Report

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#190]
Status icons are not vertically centred: https://github.com/scanapi/scanapi/issues/161#issuecomment-649146809

<img width="184" alt="Screen Shot 2020-06-24 at 8 39 44 PM" src="https://user-images.githubusercontent.com/235208/85640841-e1cf6a00-b65a-11ea-937f-72b2860076c2.png">

**Comment by abreumatheus** [comment]
I created a PR fixing this issue [#195] 😄

**Comment by barbosa** [comment]
Closed by #195 

Thank you, @abreumatheus !
