### ISSUE TITLE
ADR 6: How to integrate feature that converts OpenAPI file to ScanAPI file

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#202]
## Architecture Decision Review - ADR

We want to implement the feature of receiving a JSON OpenAPI spec and convert it into a ScanAPI spec file.

```
Receive a json OpenAPI spec -> return an api.yaml file
```

Feature issue: https://github.com/scanapi/scanapi/issues/12

But we need to discuss how we will integrate it into the main project. Some options that came into my mind:

### Option 1

A new command like: `$ scanapi init OPENAPI_PATH`. And leave the main command as it is.

(we would need to investigate if it is easy to do that with Click, but I believe with groups is quite feasible.)

###  Option 2

A new command like: `$ scanapi init OPENAPI_PATH` and change the main command to something like `$ scanapi run SPEC_PATH`

(we would need to investigate if it is easy to do that with Click, but I believe with groups is quite feasible.)

###  Option 3

A new command like: `$ scanapi-init OPENAPI_PATH`. And leave the main command as it is

(This would be pretty easy to implement with Click)

---

Maybe `generate` instead of `init`, don't know 🤷‍♀️

I like the options 1 and 2. For me, the downside of 2 is that we would need to change the way it is now. And the downside of 1 is that for some cases we will use `scanapi` directly and for other with another command, which is not so intuitive and it is also not a pattern. Option 3 is easier but I dislike it because it is ugly 😂 

Do you have more ideas? What do you think about this ones? @barbosa @gillianomenezes @djalmaaraujo @abreumatheus

**Comment by djalmaaraujo** [comment]
@camilamaia From what I understood, this is a Developer UX problem. If you think about the person who is implementing this on their CI for example, the first thing they will try to do is read the documentation to put this to work as soon as possible.

My suggestion to avoid miss interpretation of the developer who is using scanapi is to use the same command as we use now, and internally if it's a JSON, you can redirect the code to understand JSON API. 

After that, you can basically update the documentation saying: "If you already have a JSON API file, you can pass the file path and scan API will handle for you".

My 2 cents ;)

**Comment by gillianomenezes** [comment]
To be able to use OpenAPI file is an awesome idea, @camilamaia! 🚀But if I understood the discussion here well, I think that running the scanapi to convert the openapi spec to the scanapi spec is gonna just add an extra step in the flow, as the user probably wants to create the scanapi report with the converted file anyway. Maybe if the scanapi accepts the json openapi as input to create the reports, this is going to be more straightforward for the user as @djalmaaraujo said. But, as I said previously, maybe you foreseeing a scenario that I am missing. What do you think? 😃

**Comment by abreumatheus** [comment]
Yeah, in my opinion the best choice would be to just add a flag to the main
command, so it could accept a json file insteand of a yaml file. Maybe like
scanapi - - json JSON_FILE_PATH, or anything like it 😁.

**Comment by camilamaia** [comment]
Hmmm I haven't thought about this idea 🤔 It makes sense....

I was thinking more in creating a `skeleton` of the ScanAPI spec. Because there is some information that we will not have in the openapi json. For example, the tests will not be there. 

```
tests:
    name: foo
    assert: ${{...}}
```

Also, we would no be able to chain the requests. Or how would we handle authentication? OpenAPI json would not contain credentials. We would loose these features.

My suggestion is to create only a skeleton of the ScanAPI spec and the user can, manually, improve it as he/she wants. To add authentication, tests, chain requests and so on.

**Comment by abreumatheus** [comment]
I put some thought into it and really makes more sense to give the user the converted YAML file, because it's obvious he will want to add the tests and everything else. So i would vote for a new argument like `scanapi generate JSON_FILE_PATH`.

**Comment by barbosa** [comment]
Agreed this should be a generated boilerplate/skeleton. There's more stuff to be added afterward.

About the options, I'd go with 2. Having a `run` command makes it also more explicit (we could maybe make it the default option as well if needed).

And what do you think of using `convert` instead of `generate`? In the end, we are _converting_ an OpenAPI spec to a ScanAPI spec.

**Comment by abreumatheus** [comment]
I agree with Gustavo on this. :)

**Comment by camilamaia** [comment]
+1 to option 2 using `convert` instead of `generate`.

**Comment by djalmaaraujo** [comment]
+1 for @barbosa idea and `convert` instead of generate.

**Comment by camilamaia** [comment]
Ok, it seems we have a decision here. I updated the issue https://github.com/scanapi/scanapi/issues/12 with the new instructions and I will close this one, ok?

Let me know if you want to discuss anything else, so I can reopen it.

**Comment by gillianomenezes** [comment]
+1 for @barbosa idea of using convert instead of `generate`.
