### ISSUE TITLE
Change config file default name

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#203]
Our default config path is `.scanapi.yaml`, which is not so explicit as it could.

https://github.com/scanapi/scanapi/blob/master/scanapi/settings.py#L5

Some other possibilities:

- scanapi.conf (like [redis](https://redis.io/topics/config), or [postgresql](https://www.postgresql.org/docs/9.3/config-setting.html))
- scanapi.init (like [pytest](https://docs.pytest.org/en/latest/customize.html))
- .scanapi (like [rspec](https://github.com/rspec/rspec/wiki#rspec))

My favorite one is the first, because in my opinion it is the most explicit. 

Besides we also need to:
- Update documentation at [scanapi/website](https://github.com/scanapi/website/tree/master/_docs_v1) 
- Update examples at [scanapi/examples](https://github.com/scanapi/examples)

**Comment by supakeen** [comment]
Hey there, would you want to perhaps follow the ``XDG`` rules for where command line files have to go? In that case we could use ``appdirs`` to determine the folder perhaps with an override if the file exists in the current working directory scanfile is being ran from (this might be confusing).

Filename wise I like using XDG paths for global configuration and the ``scanapi.conf`` format if it's taken from the working directory.

**Comment by camilamaia** [comment]
@supakeen I did not know about the XDG pattern, now many things on my life makes sense 😂 I love the idea. And yes `scanapi.conf` sounds good for the working directory.

I update the issues to remind us to update docs and also examples. Since this is a breaking change feature, we have to also think how are we going to handle previous versions. The same for the issue https://github.com/scanapi/scanapi/issues/204
