### ISSUE TITLE
Change API spec file default name

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#204]
Current the default name for the API spec is `api.yaml`. One suggestions is to change it to something more common in the industry like `Scanfile` (similar to [Fastfile](https://docs.fastlane.tools/advanced/Fastfile/#fastfile) or [Dockerfile](https://docs.docker.com/engine/reference/builder/))

https://github.com/scanapi/scanapi/blob/master/scanapi/settings.py#L10

Besides we also need to:
- Update documentation at [scanapi/website](https://github.com/scanapi/website/tree/master/_docs_v1) 
- Update examples at [scanapi/examples](https://github.com/scanapi/examples)

**Comment by supakeen** [comment]
I'll take this :)

**Comment by supakeen** [comment]
How would you want to deal with the current checks regarding the filename extension to determine the file format, I see two options.

My current implementation renamed ``api.yaml`` to ``Scanfile`` which is a name I like a lot.

We could:
1. Try to parse the file as the various supported serialization formats.
2. Add a shebang-like identifier at the top.
3. Include a filename extension.

**Comment by camilamaia** [comment]
Good question! I would go with the option number 1, because it is more intuitive for the user. 

I believe [PyYAML](https://pyyaml.org/wiki/PyYAMLDocumentation) already tries to do that.

```python
In [13]: yaml.safe_load("""
    ...: foo, bar, hi
    ...: """)
Out[13]: 'foo, bar, hi'

In [14]: yaml.safe_load("""
    ...: x: foo
    ...: y: bar
    ...: z:
    ...:     - 1
    ...:     - 2
    ...: """)
Out[14]: {'x': 'foo', 'y': 'bar', 'z': [1, 2]}
```

We could add a check if the object generated by PyYAML is not a dict, then we raise an error that the file is invalid, for example.

What do you think @supakeen? @barbosa any thought on that?

@supakeen I also update the ticket to remind us to update doc and examples.
