### ISSUE TITLE
Increase spec_evaluator.py coverage

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#221]
Improve coverage of `/scanapi/evaluators/spec_evaluator.py` file to > 90%
It is the only file that has coverage < 90% right now.

**Comment by chinvib66** [comment]
@camilamaia, I would like to work on this issue. 

I have a query
In SpecEvaluator, if endpoint.parent is None, which is by default None, then get(key) function throws error. Should I add exception handling in the get function, or leave it as it is?

**Comment by chinvib66** [comment]
Also, in Endpoint class, in `spec` property `VARS_KEY` is not allowed, but it is used to set the `vars` property. Refer to `scanapi/tree/endpoint_node.py` line 41.

**Comment by camilamaia** [comment]
> Also, in Endpoint class, in `spec` property `VARS_KEY` is not allowed, but it is used to set the `vars` property. Refer to `scanapi/tree/endpoint_node.py` line 41.

@chinvib66 great catch! I am thinking the best way to solve this 🤔 I believe we could make vars allowed to endpoints node too in this case.

**Comment by camilamaia** [comment]
> @camilamaia, I would like to work on this issue.
> 
> I have a query
> In SpecEvaluator, if endpoint.parent is None, which is by default None, then get(key) function throws error. Should I add exception handling in the get function, or leave it as it is?

@chinvib66 sorry, on which line? The root node is the only node that does not have a parent.

**Comment by chinvib66** [comment]
`/scanapi/evaluators/spec_evaluator.py` line 38, the `__getitem__` function, which is used by `get` function (line 29).

In `__getitem__` function, if you look at line 42, the if condition is valid only if `self.endpoint.parent` is **not** `NoneType`

So, for root node, as you said, the parent will be `None`, and the invalid if condition raises `AttributeError`, which is not handled in any of the two functions.

**Comment by camilamaia** [comment]
> `/scanapi/evaluators/spec_evaluator.py` line 38, the `__getitem__` function, which is used by `get` function (line 29).
> 
> In `__getitem__` function, if you look at line 42, the if condition is valid only if `self.endpoint.parent` is **not** `NoneType`
> 
> So, if `endpoint` of some `SpecEvaluator` object is root node, for which the parent will be `None`, then the invalid if condition raises `AttributeError`, which is not handled in any of the two functions.

Got it, that makes sense. It would be nice to have this handled in fact.

**Comment by camilamaia** [comment]
@chinvib66 I will close this issue, since you PR already solved it, but I believe we can create new issues to the edge cases you pointed out.

**Comment by chinvib66** [comment]
> `/scanapi/evaluators/spec_evaluator.py` line 38, the `__getitem__` function, which is used by `get` function (line 29).
> 
> In `__getitem__` function, if you look at line 42, the if condition is valid only if `self.endpoint.parent` is **not** `NoneType`
> 
> So, if `endpoint` of some `SpecEvaluator` object is root node, for which the parent will be `None`, then the invalid if condition raises `AttributeError`, which is not handled in any of the two functions.

@camilamaia Please note that my PR did not handle the issue as you were yet to reply to my comment at that time.
