### ISSUE TITLE
Move documentation from README.md to the website

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#227]
Move `Documentation` section of the README.md to [the website doc](https://github.com/scanapi/website/tree/master/_docs_v1). 

![image](https://user-images.githubusercontent.com/2728804/88465412-3869d700-ce99-11ea-9e40-6c8f5d4b4dd8.png)

We also need a link to the Website [scanapi.dev](scanapi.dev) in the README.md

**Comment by 5pence** [comment]
will give this a go

**Comment by 5pence** [comment]
Have completed this story - suggest creating a new issue to: 

We also need a link to the Website scanapi.dev in the README.md
as that is for the scanapi repo?
