### ISSUE TITLE
Change `project-name`, `hide-request` and `hide-response` to use underscore

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#228]
Change `project-name`, `hide-request` and `hide-response` to use underscore

- `project_name` instead of `project-name`
- `hide_request` instead of `hide-request`
- `hide_response` instead of `hide-response`

https://github.com/scanapi/scanapi/blob/55e30aa92aed6a3a1131e35f357aff2fbdd61bc8/scanapi/reporter.py#L36
https://github.com/scanapi/scanapi/blob/55e30aa92aed6a3a1131e35f357aff2fbdd61bc8/scanapi/hide_utils.py#L14-L15

**Comment by Pradhvan** [comment]
@camilamaia I can pick this up ✋
