### ISSUE TITLE
Status Circle misaligned

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#233]
For some users, the status circle in the report in misaligned

![image](https://user-images.githubusercontent.com/2728804/88477974-f2555780-cf1a-11ea-8ba0-24c23e881464.png)

I testes using Mac for Safari, Chrome and Firefox and they all work. Probably something related with OS? 

Does anyone use linux/windows here? So then we can test it better :)

**Comment by Pradhvan** [comment]
@camilamaia I can test it out in a Linux system. But I don't know where can I check the CircleCI icon ?

**Comment by camilamaia** [comment]
@Pradhvan oh it is not the circleci icon, it is the circle in the ScanAPI Report.

![image](https://user-images.githubusercontent.com/2728804/89447175-f4de5b00-d72b-11ea-945c-034bfdf5a111.png)

For me, the green `P` circle is aligned, but for others users is appears misaligned, like this:

![image](https://user-images.githubusercontent.com/2728804/88477974-f2555780-cf1a-11ea-8ba0-24c23e881464.png)

For testing, you can open the report example in a brownser: https://github.com/scanapi/examples/blob/master/pokeapi/scanapi-report.html

If you want to run the report locally, here are the steps:

- https://github.com/scanapi/scanapi/blob/master/CONTRIBUTING.md#run
- https://github.com/scanapi/scanapi/blob/master/CONTRIBUTING.md#clone-scanapi-examples

**Comment by Pradhvan** [comment]
Oh ! My bad 😓 Let me check that tomorrow on a Linux system. 😄

**Comment by camilamaia** [comment]
@Pradhvan hey, did you have a chance to test it? I want to fix it, but I can't reproduce it 😞

**Comment by Pradhvan** [comment]
@camilamaia hey ! Will update this by tomorrow EOD for sure.  Had been a bit busy so didn't get a chance to do it.
