### ISSUE TITLE
Document how to set Content-Length 0 for GET

### ISSUE THREAD

**Issue by malminhas** [scanapi/scanapi#237]
ScanAPI appears to set body to `{}` and `Content-Length` to 2 in every GET request.  This results in an error with a particular endpoint I am trying to hit which requires an empty body with Content-Length=0.   I tried to set `body: ""` but that didn't override the default behaviour.  Eventually I figured out that I could set the body empty in the GET like this: 

`body: `

it then sets Content-Length to 0 and the GET call works.  I think it would be useful to document this.

**Comment by camilamaia** [comment]
What we could do is to properly set the body as None in the GET request. This way we would have the expected behaviour.
What do you think @malminhas?

I am going to close this issue since I created a new one to change the ScanAPI behaviour, ok? https://github.com/scanapi/scanapi/issues/262

**Comment by malminhas** [comment]
Sounds ideal to me @camilamaia, thanks for the heads up.
