### ISSUE TITLE
Publish Sphinx Documentation

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#242]
## Publish Sphinx Documentation
The #230 implemented the auto-generated code documentation using [sphinx](http://sphinx-doc.org/).

We can run it locally by running

```shell
$ cd documentation
$ make html
```

And we can access it opening the file `scanapi/documentation/build/html/index.html` in a browser.

This is great, but it would be nice to have this documentation published somewhere else. One option would be to publish it inside our website [scanapi.dev](https://scanapi.dev), repository: https://github.com/scanapi/website

**Comment by 5pence** [comment]
Yes can add this in Camila :) will assign myself

**Comment by camilamaia** [comment]
Maybe a good reference of how to do this: https://github.com/marketplace/actions/sphinx-build

**Comment by camilamaia** [comment]
Hey, @5pence are you still working on this? Or should I clean the assignees up?

**Comment by jhermann** [comment]
Just as a note, the more common subdir is `docs`.

And a nice feature to have is starting a `sphinx-autobuild` demon so any change in your editor triggers a rebuild and then a reload in your browser.

**Comment by jhermann** [comment]
If you go with RTD, the relevant docs is [Incoming Webhooks and Automation — Read the Docs 5.21.0 documentation](https://docs.readthedocs.io/en/stable/webhooks.html) and is almost effortless usually.

`docs.scanapi.dev` could be added as a CNAME for the RTD domain.

**Comment by Pradhvan** [comment]
I agree with @jhermann let's go with Read The Docs with Furo Theme that [urlib3](https://urllib3.readthedocs.io/en/stable/) uses. 

>docs.scanapi.dev could be added as a CNAME for the RTD domain.

Yes, this would make sense.

**Comment by camilamaia** [comment]
💯 agreed: 

- Read The Docs + Furo Theme
- docs.scanapi.dev CNAME for the RTD domain

I can set the CNAME once we have all configured for the RTD domain.

@jhermann do you want to go ahead and do the setup of the RTD?

**Comment by Pradhvan** [comment]
I can work on this too. RTD is something I have been wanting to try out. 😄

**Comment by jhermann** [comment]
@Pradhvan we can do this together tomorrow, especially regarding using the right RTD account (yours or Camila's).

Also, I wonder what's in documentation right now – API docs only? If yes, the option to switch to my normal Sphinx setup would be feasible and has some advantages regarding many conveniences already built in.
→ https://github.com/Springerle/py-generic-project/tree/master/%7B%7Bcookiecutter.repo_name%7D%7D/docs

See https://confluencer.readthedocs.io/ for an example rendering.

**Comment by camilamaia** [comment]
@Pradhvan, @jhermann 
I did the RTD setup: https://scanapi.readthedocs.io/en/latest/. It is still not rendering as expected 🤔  many docstrings are not there. Like, [hide_utils](https://github.com/scanapi/scanapi/blob/main/scanapi/hide_utils.py)  for example.

@jhermann It would be nice to have the docs of all docstrings, from all methods/classes. Public and private I guess. I love your cookiecutter and how it is rendered. +1 to use your structure.

**Comment by jhermann** [comment]
OK, I'll work on a replacement -- things like hidden symbols should be handled, because I already have these things in conf.py. Will not be ready today, but likely in the course of next week.

**Comment by camilamaia** [comment]
@jhermann awesome! I will create a new issue for it and close this one, ok? Since this is pretty much done.

**Comment by camilamaia** [comment]
@jhermann here is the new issue: https://github.com/scanapi/scanapi/issues/469

Would mind sending a comment there saying you want to work on it so I can assign it to you?
