### ISSUE TITLE
Create a dockerhub account for ScanAPI organization

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#243]
## Create a dockerhub account for ScanAPI organization

Currently we are using my private account (camilamaia) to store ScanAPI's docker images: https://hub.docker.com/r/camilamaia/scanapi. We need an organization account.

**Comment by marcuxyz** [comment]
Can i help u?

**Comment by camilamaia** [comment]
> Can i help u?

I make a mistake, create the org scanapi, but I had to delete it. Now I can't get the same name `scanapi`, it says is already taken. I sent an email but no replies till now :/

**Comment by marcuxyz** [comment]
I try speak with docker organization, but, unsuccessfully. Sorry!

I go close the issue, but, re-open when you want;

**Comment by camilamaia** [comment]
We need to pay to have an organization now, unfortunately

https://hub.docker.com/choose-plan?type=organization

Closing the issue for now...
