### ISSUE TITLE
Newcomers contribution guide

### ISSUE THREAD

**Issue by Pradhvan** [scanapi/scanapi#245]
Add in `contributions.md` or create a newcomers guide that follows an approach for better commit messages and gives out better git practices for newcomers/first time contributors to follow. 

Good docs shared by @vinigfer 

[0]https://seesparkbox.com/foundry/semantic_commit_messages
[1]https://chris.beams.io/posts/git-commit/

**Comment by camilamaia** [comment]
hey @Pradhvan I've created the guide inside our wiki! Let me know what you think about it 😄
