### ISSUE TITLE
Create new Labels for Issues

### ISSUE THREAD

**Issue by marcuxyz** [scanapi/scanapi#255]
I was thinking, we could create labels:

`easy`
`hard`

This would help new members.

**Comment by camilamaia** [comment]
@marcuxyz I like the idea! I am just not sure about how to categorize the issues. How can we define if a issue is easy or hard?

**Comment by marcuxyz** [comment]
> @marcuxyz I like the idea! I am just not sure about how to categorize the issues. How can we define if a issue is easy or hard?

Yeah... hahahahaha I have ideia. e.g:

#### Easy

- all documentation parts
- add minimal things
- minimal bug fix 

#### Hard

- bug in deploy process
- and etc...

what do you think?
