### ISSUE TITLE
Add anchor link for each request in the report to make it easily shareable

### ISSUE THREAD

**Issue by loop0** [scanapi/scanapi#260]
It would be nice to have [anchor links](https://visualcomposer.com/blog/what-is-anchor-link/) available at each request in the report. 

To share a specific request that needs review would be easier than having to scan (pun intended) through the entire report.

**Comment by 07carvalho** [comment]
if it's ok, I can get this task

**Comment by camilamaia** [comment]
> if it's ok, I can get this task

Sue thing! Let us know if you need any help @07carvalho 🎉

**Comment by camilamaia** [comment]
Hey @camilamaia, are you still working on this? Or should I clean the assignees up? Thank you!

**Comment by 07carvalho** [comment]
sorry, i'm moving to another city and couldn't work in this issue. i am unassigning

**Comment by camilamaia** [comment]
@07carvalho don't worry! Not a problem at all. I hope you enjoy the new city 🎉 🏙️

**Comment by pxd3v** [comment]
I would love to work on it, can i pick it up?! =)

**Comment by camilamaia** [comment]
> Hi @camilamaia, I would love to work on it, can I pick it up?! =)

Sure, thanks! I will assign you ☺️

**Comment by pxd3v** [comment]
@camilamaia hey! I'm kinda confused about the issue, just to make it clear, the objective is to implement anchor links for each one of those? Or an endpoint can have more than one "Request" section?!
![image](https://user-images.githubusercontent.com/55694628/96370033-f1574f00-1132-11eb-932d-43471cbaf8f4.png)

**Comment by camilamaia** [comment]
@pxd3v you are correct, it should be one per each line in the picture. One for each endpoint class. 

One endpoint, in the report, has always exactly one request and one response header.

**Comment by pxd3v** [comment]
Thanks for the guidance! I will work on it asap!

**Comment by camilamaia** [comment]
Closed by #317
