### ISSUE TITLE
Body in the report should be rendered according to it's request content type

### ISSUE THREAD

**Issue by loop0** [scanapi/scanapi#261]
Today the Body is showing the representation of python's byte string, which in the report should be agnostic of language, but based on it's request content type.

For example:

- A request of application/json can render the body as json in the report and make use of the same tool that is used at the Content field
- A request of binary content type should just show a placeholder text like: "Binary content"
- A request of text content type should show as a text without python's representation

**Comment by beatorizu** [comment]
@camilamaia I would like to try this issue
