### ISSUE TITLE
GET requests are sending body as `{}` and Content-Length equals 2

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#262]
On GET every request ScanAPI is sending body as `{}` and Content-Length equals `2`. The body should be None and the Content-Length should be `0`.

A small hack to fix this while we don't have a new version is to have an empty body in the GET request specification, like this:

```yaml
path: /example
method: get
body:
```

Related to: https://github.com/scanapi/scanapi/issues/237

**Comment by malminhas** [comment]
Thanks @camilamaia this would be a good workaround.
