### ISSUE TITLE
Snippets Copy Button in the Report

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#263]
## Snippets Copy Button in the Report

It would be nice if the user could have a button to copy data from the report, something like this:

![image](https://user-images.githubusercontent.com/2728804/91338345-2be3e180-e7ab-11ea-8271-b9482e724f6f.png)
https://docs.api.getpostman.com

We could have it for the `cURL` and `content` blocks.

![image](https://user-images.githubusercontent.com/2728804/91338715-bb899000-e7ab-11ea-9eee-7b14de53f14d.png)
![image](https://user-images.githubusercontent.com/2728804/91338787-d22fe700-e7ab-11ea-9c8b-b30892c908cd.png)

**Comment by quizhpi** [comment]
@camilamaia I'll gladly make the update.

**Comment by camilamaia** [comment]
closed by #295
