### ISSUE TITLE
Show link to report in CLI

### ISSUE THREAD

**Issue by 07carvalho** [scanapi/scanapi#264]
Is it possible to insert a link to open the report in the end of CLI message?

![image](https://user-images.githubusercontent.com/6222601/91376098-b996ef80-e7f2-11ea-90bb-67c2856d60c6.png)

**Comment by camilamaia** [comment]
I believe it is already there. maybe it is no showing as a link for some terminals...

![image](https://user-images.githubusercontent.com/2728804/91452782-60ac7300-e855-11ea-97dd-736df43cc39a.png)

At my terminal, it shows like this:

![image](https://user-images.githubusercontent.com/2728804/91453004-a1a48780-e855-11ea-9a1b-4befe787f2b2.png)


But if I  `cmd + click` on it, it shows the link and opens it:

![image](https://user-images.githubusercontent.com/2728804/91453077-b5e88480-e855-11ea-815c-4af33064533c.png)

Would you mind to try it @07carvalho?

**Comment by camilamaia** [comment]
I tested it in another terminal and it does not work trying to click in the name. We could at least print the whole file path. I believe this would solve the problem. It might be super annoying having to get the whole path.

**Comment by leogregianin** [comment]
In reporter.py:
```python
from os.path import abspath

logger.info(f"It is available at {abspath(self.output_path)}")
```
Wouldn't that be enough to show the full path?

**Comment by camilamaia** [comment]
@leogregianin yes, I believe so!
