### ISSUE TITLE
New feature: run without report file

### ISSUE THREAD

**Issue by flap** [scanapi/scanapi#268]
I think that if I will run scanapi many times, the report generation may causes overhead in executions.
With an option --with-report, the response as a boolean can possibility performance executions.

**Comment by JRubics** [comment]
Hi, if it is ok, I would like to add this feature :)

**Comment by camilamaia** [comment]
@JRubics I've assigned you to this issue since you have a PR opened solving it, ok?

**Comment by JRubics** [comment]
@camilamaia ok :smile:

**Comment by camilamaia** [comment]
https://github.com/scanapi/scanapi/pull/299#issuecomment-865230271
