### ISSUE TITLE
Consider using flake8 and isort

### ISSUE THREAD

**Issue by kelvins** [scanapi/scanapi#270]
Hello, this is just a suggestion to consider using [flake8](https://flake8.pycqa.org/en/latest/) and [isort](https://github.com/PyCQA/isort) to improve code quality.

With flake8 we could catch things like this:
- Lines too long (e.g. > 79 characters)
- Unused imports
- Imports that were not declared at the top of the file
- ...

And using isort we could automatically sort imports based on PEP8 recommendations.

**Comment by camilamaia** [comment]
Hi @kelvins, thanks for the suggestion!

We already use black for lint in the [pre-commit](https://github.com/scanapi/scanapi/blob/master/.pre-commit-config.yaml#L1) and also in the [pipeline](https://github.com/scanapi/scanapi/blob/master/.github/workflows/lint.yml#L4), which I believe replaces flake8. 

But isort is definitely something we could have. Thank you again!

**Comment by marcuxyz** [comment]
@camilamaia consider use [autoflake ](https://pypi.org/project/autoflake/)for remove` unsed variables` and` isort to remove unsed imports and re-imports.`

@kelvins this line code, reflecting the same issue that the flake8 fix.

https://github.com/scanapi/scanapi/blob/ddd813928c667a71d836aa74ea0233b24f885e1d/Makefile#L7
