### ISSUE TITLE
Move pytest config to pyproject.toml

### ISSUE THREAD

**Issue by kelvins** [scanapi/scanapi#276]
Suggestion:
By moving the pytest configuration to `pyproject.toml` it would be possible to remove the `pytest.ini` file.

Note that the [pyproject support](https://docs.pytest.org/en/stable/customize.html#pyproject-toml) was included in pytest version 6.0 and I'm not sure if there is a specific reason (e.g. dependency conflict) that makes it impossible to update pytest right now.

**Comment by marcuxyz** [comment]
I close the issue, why it was resolved in #283
