### ISSUE TITLE
Trying to get a TOKEN from application/x-www-form-urlencoded using username and password

### ISSUE THREAD

**Issue by zimbres** [scanapi/scanapi#300]
Hello,

I trying to validating the authentication of FastAPI implementation with no success.

I tried to get the token from username=johndoe&password=secret but looks like sending body: username=johndoe&password=secret is double quoting the -d parameter, I got 422 response

Even so I tried to authenticate by Bearer genereate by swagger endpoint also with no success, I got an 307 response.

Is this kind of scenario implemented? The definitions in my APÌ is exactly the same o FastAPI Security example.

**Comment by zimbres** [comment]
Bearer token directly is fine, my mistake about /endpoint.

Only error is get a Token from username and Password

**Comment by zimbres** [comment]
Getting TOKEN by username and password also working, the body has to be sent like:

"grant_type=&username=johndoe&password=secret&scope=&client_id=&client_secret="

**Comment by deividfortuna** [comment]
Looks like I'm having a similar issue '"having double quoting"' in the body, how did you work around this @zimbres?
