### ISSUE TITLE
Enable `vars` key at the Endpoint level

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#302]
## Enable `vars` key at the Endpoint level

Currently, the `vars` key is only accepted at the `requests` level. It would be nice to have it also at the `endpoint` level

**Comment by gillianomenezes** [comment]
Hi @camilamaia! Can I assign it to myself?

**Comment by camilamaia** [comment]
@gillianomenezes yes sure, my friend! Make yourself at home 😄
