### ISSUE TITLE
Add video to readme.md

### ISSUE THREAD

**Issue by marcuxyz** [scanapi/scanapi#308]
Hi guys, recently @camilamaia has been create an video speak about ScanApi.  will we add the video in readme on example session?

![image](https://user-images.githubusercontent.com/9499562/95585164-3bdf1a00-0a15-11eb-8f29-8d7b30f60af2.png)

Video link:
https://www.youtube.com/watch?v=JIo4sA8LHco&t=2s

**Comment by morvanabonin** [comment]
Hi Marcus,

a question, 

do you want only put a link as the image example or embed as shown in this example -> https://qastack.com.br/programming/4279611/how-to-embed-a-video-into-github-readme-md?

I wait for your response.

**Comment by marcuxyz** [comment]
Thanks you to reply.
You're right!

I'll think good that. Thanks

**Comment by marcuxyz** [comment]
> Hi @marcuxyz,
> 
> a question,
> 
> do you want only put a link as the image example or embed as shown in this example -> https://qastack.com.br/programming/4279611/how-to-embed-a-video-into-github-readme-md?
> 
> I wait for your response.

Thanks you to reply.
You're right!

I'll think good that. Thanks

**Comment by morvanabonin** [comment]
Right! So, I'll do that way.

**Comment by morvanabonin** [comment]
How I save the image to use?
https://raw.githubusercontent.com/scanapi/scanapi/master/images/

**Comment by marcuxyz** [comment]
> How I save the image to use?
> https://raw.githubusercontent.com/scanapi/scanapi/master/images/

Here...404 erro this link

**Comment by morvanabonin** [comment]
Yes! I noticed that was the link of the images in the other examples, but I did not send the image I created yet.
Do you have an email that I can send the image?
Sorry for this bunch of questions, but I'm familiarizing with the project.
Thanks for your help.

**Comment by marcuxyz** [comment]
Yes i do. Please send me:

preto@marcuspereira.xyz

Sorry my lag to reply.

**Comment by camilamaia** [comment]
Closed by #338

**Comment by morvanabonin** [comment]
Thanks, @camilamaia!

As I said to @marcuxyz, I jumped some steps of the doc, so to me was good to review them and learned more about it. Some tools you use to build the scanapi are very useful. I think I can use in my jobs projects as well. <3

**Comment by camilamaia** [comment]
@morvanabonin I am super glad to hear that! And please let us know if you need any help!! 🚀
