### ISSUE TITLE
Wiki - Run ScanAPI Locally

### ISSUE THREAD

**Issue by flaviotruzzi** [scanapi/scanapi#312]
Hi,

I was following the [wiki](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally), it looks like the documentation there is outdated with the current state of the project.

It says:

```bash
poetry run scanapi ../examples/pokeapi/scanapi.yaml -c ../examples/pokeapi/.scanapi.yaml -o ../examples/pokeapi/scanapi-report.html
```

However the example structure does not follow that:

```bash
> tree examples/pokeapi
examples/pokeapi/
├── README.md
├── scanapi.conf
├── scanapi-report.html
└── scanapi.yaml
```

From the help I got it running with:
```
> poetry run scanapi run examples/pokeapi/scanapi.yaml -c examples/pokeapi/scanapi.conf -o examples/pokeapi/scanapi-report.html
Loading file examples/pokeapi/scanapi.conf
Loading file examples/pokeapi/scanapi.yaml
Writing documentation
Making request GET https://pokeapi.co/api/v2/pokemon
Making request GET https://pokeapi.co/api/v2/pokemon/bulbasaur

The documentation was generated successfully.
It is available at /home/[omitted]/examples/pokeapi/scanapi-report.html
```

Did I miss something?

**Comment by marcuxyz** [comment]
You really are super right! This will be corrected ...

as documentation:
![image](https://user-images.githubusercontent.com/9499562/97433467-544ba180-18fc-11eb-9545-73e0fb562c25.png)

with fixed:

![image](https://user-images.githubusercontent.com/9499562/97433578-7f35f580-18fc-11eb-92ea-9447e29b7c55.png)
