### ISSUE TITLE
Wiki  - Python version

### ISSUE THREAD

**Issue by flaviotruzzi** [scanapi/scanapi#313]
Hi,

On the [wiki](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally) it says you need python3.

Looks like poetry do fine with any version of python3, but the configuration for black on the precommit enforces python 3.7, and you need to have it installed to be able to commit or it fails with:

```
➜  scanapi git:(298) ✗ git commit
[INFO] Installing environment for https://github.com/python/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/ftruzzi/.cache/pypoetry/virtualenvs/scanapi-p1C8APXn-py3.8/bin/python', '-mvirtualenv', '/home/ftruzzi/.cache/pre-commit/repos689y0ty/py_env-python3.7', '-p', 'python3.7')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7'
    
stderr: (none)
Check the log at /home/ftruzzi/.cache/pre-commit/pre-commit.log
```

To fix it I had to delete the virtualenv, reset my pyenv to a 3.7, reinstall poetry under this version.

Is there some other workaround for this?

**Comment by marcuxyz** [comment]
in the https://github.com/psf/black, say:

![image](https://user-images.githubusercontent.com/9499562/97432712-26199200-18fb-11eb-84d7-e802355825ed.png)

in the pre-commit documentation say:

![image](https://user-images.githubusercontent.com/9499562/97432599-fb2f3e00-18fa-11eb-9433-cb5e947e7b52.png)

I believe that above this version both should work. I believe that good leave this clean @camilamaia

**Comment by marcuxyz** [comment]
Fix!!!
