### ISSUE TITLE
Add flake8 python style formatting to pre-commit

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#322]
## Add flake8 Python style formatting to pre-commit

File to add configuration: https://github.com/scanapi/scanapi/blob/master/.pre-commit-config.yaml
More info at: https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/

Configuration should match with flake8 github action check: https://github.com/scanapi/scanapi/pull/321

**Comment by NimishVerma** [comment]
Hi, I would like to work on this.  The configuration repo seems to be private or non-existent since it returns 404.

**Comment by camilamaia** [comment]
> Hi, I would like to work on this. The configuration link seems to be private or non-existent since it returns 404.

Hi! It is because the PR was not merged yet. But I changed the description with a proper link, thanks!

I will assign this issue to you 👍

**Comment by camilamaia** [comment]
Closed by #323
