### ISSUE TITLE
Commit Patterns

### ISSUE THREAD

**Issue by marcuxyz** [scanapi/scanapi#329]
what do you think about adopting this standard? For new commits

https://www.conventionalcommits.org/en/v1.0.0-beta.2/

@camilamaia

**Comment by Pradhvan** [comment]
Fixing a commit pattern streamlines a lot of things @marcuxyz and would also help beginners/first-time contributors. We should fix something and add it to the wiki plus the Newcomer's section. 

Wiki link: https://github.com/scanapi/scanapi/wiki/First-Pull-Request#7-make-your-changes

**Comment by camilamaia** [comment]
@marcuxyz @Pradhvan Do you know if is there a way to automate it? We already have an instruction about commits in our wiki, but I honestly always forget about it.

https://github.com/scanapi/scanapi/wiki/First-Pull-Request#9-commit-and-push-your-changes

I think it is super important and maybe a tool would help us here.

**Comment by Pradhvan** [comment]
@camilamaia On top of my head I can't seem to remember any tool that checks git commit message. But just to ease up the process I remember you can set commit message templates like [this](https://devtutorial.io/how-to-create-a-template-commit-message-git-p1244.html) 

That can help a bit I guess until we find a method to automate the process.

**Comment by camilamaia** [comment]
@Pradhvan I like this idea! So maybe we can change this issue description to "Create a template commit message". What do you think @marcuxyz @Pradhvan? If you like it, I can update the issue.

**Comment by Pradhvan** [comment]
@camilamaia I like the idea. Just searching a bit on how to use the `commit template` for a particular project rather than having a global commit message template that shows up on every project that has `.git` repot. That might be a bit problematic. 

Also, we should give a commit template as an option and always show them to the wiki with the commit message pattern because it would be a bit difficult for newcomers to just set and update `.git` directory and set a template.

**Comment by camilamaia** [comment]
@Pradhvan We could try to automate this part of updating the .git dir and set template with the `make install` command. This way, the user wouldn't need to do anything besides running the install command

**Comment by Pradhvan** [comment]
@camilamaia yes that would solve a lot of problems. 😄

**Comment by hebertjulio** [comment]
Hey everyone,

I found this solution that can be helpful to automate commit message lint.

[commitlint-pre-commit-hook](https://github.com/alessandrojcm/commitlint-pre-commit-hook)

**Comment by camilamaia** [comment]
@hebertjulio thanks for sharing! We could definitely  use it.

**Comment by camilamaia** [comment]
I am going to close this issue since we've agreed we need a pattern and we need to automate this check. So I created a specific issue for it #438
