### ISSUE TITLE
🗣 Announcement: Holidays

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#333]
Hi! I just wanna let you all know I will be on holidays the next week, so I will not work on ScanAPI during this period.

Thanks everyone that contributed, especially during the Hacktoberfest, and I am sorry for the ones we could not merge the PR yet.

It takes a lot of time to review and check all the PRs and we prefer to not merge the ones we didn’t have the proper time for this evaluation.

Thank you all! And see you soon 🏖

**Comment by Pradhvan** [comment]
@camilamaia have fun 😄 🍹

**Comment by camilamaia** [comment]
I am back 😎
