### ISSUE TITLE
JSON of results in template

### ISSUE THREAD

**Issue by leandro-hermes** [scanapi/scanapi#353]
Hey, guys! Is there a way to pass the `results` key as a JSON to the template? I don't know anything about Python, but I would like to present the results in a different way in my template. Thanks!

**Comment by camilamaia** [comment]
@leandro-hermes great question. I am working to add this point to the documentation soon. This is the issue if you want to follow it: https://github.com/scanapi/website/issues/38

**Comment by leandro-hermes** [comment]
Grat! Thanks

**Comment by camilamaia** [comment]
@leandro-hermes finally I had some time to create the documentation page for it! Please check the page: https://scanapi.dev/docs_v1/configuration/custom_report.html

So, you have to create your jinja2 template, something like "json_template.jinja":

```
{
    "project_name": "{{ project_name }}",
    "results": [{% for result in results -%}
            {% set response = result.response %}
            {% set request = response.request %}
            {
                "url": "{{ request.url }}",
                "status_code": {{ response.status_code }}
            },
        {% endfor %}]
}
```

And then run ScanAPI passing your template in the argument:

```shell
$ scanapi run -t json_template.jinja
```

Some others references that might help:

- https://gist.github.com/sevennineteen/4400462
- https://stackoverflow.com/questions/48632585/how-to-generate-json-using-jinja2-template-engine

I am closing this issue, but don't hesitate to send more questions. I can reopen it any time.
