### ISSUE TITLE
Move the community communication channel away from Septrum 

### ISSUE THREAD

**Issue by Pradhvan** [scanapi/scanapi#376]
Hello Everyone 👋🏾 

Spectrum will become read-only on August 10, 2021.[ Official announcement post](https://spectrum.chat/spectrum/general/join-us-on-our-new-journey~e4ca0386-f15c-4ba8-8184-21cf5fa39cf5). 

Since Spectrum would be read-only I suggest moving to some other platform, a dev channel really comes in handy to interact with folks in async. Conversations that aren't fit for Github issues since a community is more than just about closing PR's. 

I had suggested Zulip in the past and here is the [thread ](https://spectrum.chat/scanapi/general/can-we-move-to-zulip~91d57217-4a5f-49fd-b00d-ab65621fe98c) on Spectrum.

Also having a communication channel helps folks to hang around after a sprint (winks EuroPython 2020 sprints) and new folks join in the conversation/give feedback after using scanapi or just hearing about it from a talk. 

Opening this thread so we can have more people chip into the convention. 

PS: Here is a quick tour of [Zulip](https://zulip.com/hello/)

**Comment by Pradhvan** [comment]
Some communities are on discord too so that can be also one of the options to consider. 😄

**Comment by Pradhvan** [comment]
That's a great plan @camilamaia ⚡ 

Though I don't like that much telegram personally as it's a bit less secure i.e when the community grows spammers start to swamp the channel. (Have seen this with local communities here).Plus would be really hard to maintain a strict COC for the telegram channel. 
On the other hand. I think we should move to discord that way we don't have to manage two different channels one for english (general public channel) and one for folks in Brazil (scanapi_br). We can have multiple stream inside discord to do that. Plus more control of bots to have a strict COC. 

Having discord would also help people share screen and pair program(Maybe we could plan a sprint once in three months. Who knows?) to solve the bug which would be hard if we go to telegram.

**Comment by hebertjulio** [comment]
I think the same thing @Pradhvan

**Comment by camilamaia** [comment]
@Pradhvan you got a point. I agree and I've already created the server: https://discord.gg/sthrWNPn. I will not spread about it now, because I need to properly set up the configuration. :)

**Comment by Pradhvan** [comment]
@camilamaia this is great. Thank you! ❤️ Looking forward to it. 

Do let me know if you need any help with it. Always happy to help. 😄

**Comment by Pradhvan** [comment]
Closing the issue now that we have finalized on where to move the community platform and how to move it. 🚀

**Comment by Pradhvan** [comment]
@camilamaia if the discord channel is open. Should we add a badge for it in the readme of the project ? We can also post that in the footer of the website ?

**Comment by camilamaia** [comment]
> @camilamaia if the discord channel is open. Should we add a badge for it in the readme of the project ? We can also post that in the footer of the website ?

Done ✅
