### ISSUE TITLE
Add missing docsting to increase coverage in interrogate

### ISSUE THREAD

**Issue by Pradhvan** [scanapi/scanapi#377]
Before merging #337 we should add missing docstrings so that the entire coverage at least bumps to 80% or more.  

The current docstring coverage:

```
RESULT: FAILED (minimum: 80.0%, actual: 11.2%)
```

**Comment by Pradhvan** [comment]
Since eventually, we would be adding all those missing docstrings. Yay! 🙌🏾

How about we set a format for the docstrings? We can start with adding them to new ones and eventually move the older docstrings to the decided format. What do you think? @camilamaia 

I personally use this format:

```
"""
The explanation goes here!

Args:
    param1 [type]: This is the first param.
    param2 [type]: This is a second param.

Returns [type]: # If anything is returned
    This is a description of what is returned.
"""
```

**Comment by Pradhvan** [comment]
Great news! I managed to move the coverage to `98.9%`  

```
RESULT: PASSED (minimum: 95.0%, actual: 98.9%)
```

Here are the `pyproject.toml` settings
```
[tool.interrogate]
ignore-init-method = true
ignore-init-module = true
ignore-magic = true
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = true
ignore-module = false
ignore-nested-functions = false
ignore-nested-classes = true
ignore-setters = false
fail-under = 95
exclude = ["documentation", "tests"]
verbose = 0
quiet = false
color = true
```

For now, I have just added a hacky solution for all the missing docstrings I have added placeholder docstrings.
```
"""Placeholder docstring"""
```

Need to now read the code, relace the placeholder docstring and add meaniful docstrings. 🤓

**Comment by camilamaia** [comment]
@Pradhvan I love the idea of having a pattern for the docstrings! We could add a step into our [First Pull Request
Doc](https://github.com/scanapi/scanapi/wiki/First-Pull-Request) explaining the need of adding docstrings and how to add them. What do you think?

**Comment by Pradhvan** [comment]
@camilamaia if you agree with the above pattern that I posted. Happy to do a PR tomorrow to add the docstring thing in the doc. 👍🏾

**Comment by Pradhvan** [comment]
@camilamaia Updated the `Make your change` section in [First Pull Request
Doc](https://github.com/scanapi/scanapi/wiki/First-Pull-Request#7-make-your-changes). Feel free to check it out and edit. 😄

**Comment by Pradhvan** [comment]
Did not know earlier going through a new codebase and adding docstrings would be this much of work. 

@camilamaia how about I push 2-3 files at a time. Would be easier to review for you too and easier for me to ask questions regarding it. What say?

**Comment by camilamaia** [comment]
@Pradhvan Thanks for the update in the docs page!

Yes, good idea, split into smaller PRs will make it easier for both you and reviewers! Cool!

**Comment by Pradhvan** [comment]
Great! Will create a PR tomorrow. 😄
