### ISSUE TITLE
Show on report the scanapi version used to generate it

### ISSUE THREAD

**Issue by hebertjulio** [scanapi/scanapi#379]
After report generated, I seen that scan api version is not shown on anywhere. I think that can be useful to know what scanapi version is running in production.

**Comment by camilamaia** [comment]
Great idea!! Maybe in the footer, something like this:

![image](https://user-images.githubusercontent.com/2728804/120035603-4286c580-bfd5-11eb-9998-17c5f8bd3ef6.png)
