### ISSUE TITLE
Create a GitHub issue Template

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#382]
## Description

Create a [GitHub issue Template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository). 

It would help us to have more info about the issues and also to make it easier to classify them.

I did not think in the content of the template yet. Maybe we could check others open sources projects to get some reference.

**Comment by Pradhvan** [comment]
Hi 👋🏾  @camilamaia 

Of what I think we can have three templates that a user chooses when clicking the issue

1) Bug report: Submit the bug report 
2) Feature request: Any feature that a user wants to see in scanapi
3) How to question: How to do 'x' with scanapi ? This can also be handled on our discord(which will be announced later) server later but having an issue here would make it open for anyone who isn't aware of the discord server.

**Comment by camilamaia** [comment]
@Pradhvan I like the suggestions! 💯 !

**Comment by camilamaia** [comment]
@Pradhvan look, this is so cool!! 🤩 

![image](https://user-images.githubusercontent.com/2728804/120538470-eea52380-c3bc-11eb-9d2e-64ac8f88ab62.png)
