### ISSUE TITLE
Create a GitHub PR Template

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#383]
## Description

Create a [GitHub PR Template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository).
 
I did not think deeply in the content of the template yet. Maybe we could check others open sources projects to get some reference. 

We could have a checklist like:
- [ ] My PR closes an existing open issue
- [ ] I ran ScanAPI locally and I manually tested my changes
- [ ] I added a changelog entry, if needed / Changelog entry is not needed
- [ ] I added/update docstrings
- [ ] I rebase my code
- [ ] Closes #<issu_number>
 ...

**Comment by Pradhvan** [comment]
@camilamaia how about this?


## Description


## Motivation behind this PR?


## What type of change is this?


## Checklist
 

- [ ] Added a changelog entry
- [ ] Added unit tests
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have Self-documented code my changes by adding docstring(s) and comment(s).
- [ ] Current PR does not significantly decrease the code coverage and docstring coverage.
- [ ] My code follows the style guidelines of this project

**Comment by camilamaia** [comment]
@Pradhvan I've added some suggestions directly to the pr https://github.com/scanapi/scanapi/pull/387#pullrequestreview-674571933

**Comment by camilamaia** [comment]
Hmmm, weird, I tested it and it seems not working 🤔 

https://github.com/scanapi/scanapi/compare/testing?expand=1

**Comment by Pradhvan** [comment]
@camilamaia let check why it's not working. 😄

**Comment by camilamaia** [comment]
@Pradhvan it works now! Thank you!!

https://github.com/scanapi/scanapi/compare/testing?expand=1
