### ISSUE TITLE
Apply to Docker Open Source Program

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#395]
### Description the feature

Current, we use Docker autobuild to automatically create new Docker images from a github release. But, this service will no longer be free:

```
Hi there, 

As one of the users of Docker Hub’s Autobuild service, we wanted to reach out and let you know that from June 18th, 2021 users on the free plan will no longer have access to the Autobuild feature. This means that any of your currently configured Autobuild will fail to run and you will need to upgrade to a Pro or Team account to restore functionality. You can read more about the changes on our blog. 

To ease this transition we are offering 20% off Docker Pro and Team for new and returning subscriptions through June 18, 2021 so you can continue using that Autobuild goodness you know and love. 

If you’re part of the Docker Open Source program, and currently leveraging Autobuilds as part of a Free plan, we want to continue supporting you and we will be reaching out to make sure you will not be impacted by this change. 

Docker is wholly focused on providing you amazing and magical experiences. We really appreciate your support and the community’s understanding as the whole industry battles against these abusive crypto miners. . 

Thanks, 

Team Docker 
```

My suggestion is to apply for their [Open Source Program](https://www.docker.com/blog/expanded-support-for-open-source-software-projects/?mkt_tok=OTI5LUZKTC0xNzgAAAF9ingUKwRDMjMLqfj3EqdfW-KT8R0R-cKF-wzKSXd7hYXlGTjB3UbiaNyQh04yuUlRpSBAwputtL14bwnKbDkpVgeKdlmnGQqslRPK3ghUbY5IjQ). This way, we would keep having the feature without costs

Also, it would be nice to have a proper ScanAPI org on docker hub: https://github.com/scanapi/scanapi/issues/243

**Comment by rodrigondec** [comment]
The Github Packages doesn't work for the project?

It has it's own docker registry, it's free (to a storage limit) for open source repos, and has nice actions to build and push!

Analyzing your images, they're about 50mb. Theoretically 10 versions could be hosted for free. Or a least the `latest` :thinking: 

Maybe do a trial run?

## Links
- https://github.com/features/packages
- https://github.com/pricing

**Comment by camilamaia** [comment]
@rodrigondec that is a great possibility, thanks for sharing it! I've just applied to docker open source program, so if we receive a no as an answer, we can definitely try Github Package as a plan B 👍
