### ISSUE TITLE
Fix security issues mentioned in static analysis

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#401]
### Description of the feature
We want to increase the code quality. We added the DeepSource tool to analyze ScanAPI code. Now, we need to fix the issues DeepSource pointed out: https://deepsource.io/gh/scanapi/scanapi/. 

- [ ] Fix security issues: https://deepsource.io/gh/scanapi/scanapi/issues/?category=security

💡  The Issue requires multiple PRs so more than one person can contribute to the issue.

**Comment by Pradhvan** [comment]
@camilamaia there are a couple of more issues[ here](https://deepsource.io/gh/scanapi/scanapi/issues/?category=security). Let's just open this issue and let other PR reference this.

**Comment by camilamaia** [comment]
There are no more security issues: https://deepsource.io/gh/scanapi/scanapi/issues/?category=security

We (@astenstrasser and I) ignored the ones we considered ok for the scope of the project
