### ISSUE TITLE
Fix style issues mentioned in static analysis

### ISSUE THREAD

**Issue by Pradhvan** [scanapi/scanapi#405]
### Description of the feature

To increase the quality of the project we are using static analysis to find out style issues in the project.

A detailed list of the issues can be found [here](https://deepsource.io/gh/scanapi/scanapi/issues/?category=style)

💡  The Issue requires multiple PRs so more than one person can contribute to the issue.

**Comment by Saransh-cpp** [comment]
Hi @Pradhvan, can I take this up under hacktoberfest?

**Comment by Pradhvan** [comment]
Hey @Saransh-cpp  👋🏾 I am not sure we would be participating in the Hacktoberfest this year. Since there a very few maintainers and core devs who help review PR(most of them are a bit busy at the moment).

Plus, sometimes Hacktoberfest creates more noise than actual participation from folks which is a bit overwhelming for folks who maintain it. 

Though feel free to take this issue if you are interested in contributing to the project in general. I would be more than happy to help you out. 😄

**Comment by Saransh-cpp** [comment]
No problem! I just saw that #509 fixes one of the errors. I'll create a PR for the redundant `pass` statements.

**Comment by astenstrasser** [comment]
Resolved by #530
