### ISSUE TITLE
Header table gets broken

### ISSUE THREAD

**Issue by rafaquelhodev** [scanapi/scanapi#409]
## UX improvement

In the report html, the header table gets broken when we have large texts
![image](https://user-images.githubusercontent.com/48420402/122487045-aa1aaa00-cfb0-11eb-8cf1-7aa1f8428ea3.png)

Perhaps a `td {word-break: break-all}` solves the problem? =) Cheers

**Comment by bartvanherck** [comment]
I created a little fix for this issue. I created a new css class and applied it to the right <td> in the tables.
