### ISSUE TITLE
Tweet from code 

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#426]
### Description the feature

To have a repo that tweet for us. We create a file in the repo, and when it is merged, it is automatically tweeted.

Pros:

- more people can tweet as the ScanAPI user
- review/approve of tweets
- no need to share secrets

### Do you have any suggestions on how to add this feature in scanapi ?

We could fork this project or implement something similar: https://github.com/loadsmart/tweets

**Comment by GitVitor** [comment]
It seems good, any progress about it?
Maybe i could help with this.

**Comment by camilamaia** [comment]
@GitVitor No progress yet. I've assigned it to you! Let me know if you need any help :)

**Comment by GitVitor** [comment]
Okay thanks Camila, i have two other issues in progress.
After there i start this new one 👍

**Comment by gagandeepp** [comment]
@camilamaia Interested in this one

**Comment by camilamaia** [comment]
Closing this issue for now 🧹
