### ISSUE TITLE
add type hints to the project

### ISSUE THREAD

**Issue by sleao** [scanapi/scanapi#431]
### Description the feature
I think it would be nice to add type hints to the codebase, as it helps with documentation, catching bugs, and to maintain the whole project.

### Is your feature request related to a problem?
Nope

### Do you have any suggestions on how to add this feature in scanapi ?
Well, you just need to specify the type of every variable/parameter. I would be glad to do it myself, if you guys agree.

**Comment by Pradhvan** [comment]
@sleao I like the idea of having type hints. @scanapi/core-team @scanapi/maintainers what do you folks think ? 

If everyone agrees let's plan it out and start adding types one file at a time. With `mypy` as a type checker in the CI as well as type checking enabled in `.deepsource.toml` config.

**Comment by hebertjulio** [comment]
I love the idea of having type hints! But I think it is a large change that can results many conflicts. The idea of @Pradhvan of adding types one file at a time reduce conflicts, but add types in all the project is a good too because we resolved it at once.

**Comment by Stannislav** [comment]
- PR for adding `mypy`: #456 
- Follow-up: fix `mypy` errors in `config_loader`: #457 
- Follow-up: add `mypy` to the CI: #458

**Comment by camilamaia** [comment]
I need to say that I don't have experience with type hints. So I want to honestly ask for you that have more XP with it:

- Is it going to make it much harder for new members to contribute? People that do not have huge XP with Python or type hints?

If we decide to go with it, I think we should have, **before we implement it**, pretty clear documentation of:
- How to use type hints
- When to use type hints 

Otherwise, we might discourage people to contribute to the project.

I was reading some stuff from @ramalho about type-hints that might guide us in this decision:

https://speakerdeck.com/ramalho/type-hints-protocols-and-good-sense
https://speakerdeck.com/ramalho/python-type-hints-take-it-easy
[PT-BR]: https://speakerdeck.com/ramalho/type-hints-em-python-pega-leve

What do you think?

**Comment by sleao** [comment]
I'm not an expert and don't know all the pros and cons of using type hints, but, I believe it actually makes it easier for new members to contribute.

First of all, it's optional, if you declare some function using type hints and decide to ignore every other function, it will work, because it doesn't change anything at runtime. It actually helps because, when calling a function or instantiating (is that even a word?) a class with type hints, it should tell you exactly what kind of parameters is expected for that call. Like docstrings do, but better, I think.

The usage is quite simple, you just need to append the type to the parameter and a `-> type` to declare the return type. See an example:
```python

def times_two(x: int) -> int:
    return x * 2
```

You can also declare lists, dicts and tuples, but depending on the python version, you need to import it from Typing. For python3.9+, you don't have to, but since we don't want to break anyones code, we should just go the old way, like this:

```python

from typing import List

def range_to_list(x: int) -> List[int]:
    return [y for y in range(x)]
```

And as a said before, since it's completely optional, you can use whenever you want, although I highly recommend it as it's one of my favorite features. Now that I think about it, I also really like to use Typescript... I should probably learn a Static typed language 🤔

**Comment by Stannislav** [comment]
I pretty much agree with what @sleao said.

I think the most important point is that it's optional and nothing should break / fail if new code doesn't have any typing at all.

There's a "strict" mode in `mypy` where types are required, but it's not on by default.

In #456 it's definitely configured to be optional. Maybe double check the settings in `.mypy.ini` to make sure you're happy with them. There are [many more](https://mypy.readthedocs.io/en/latest/config_file.html) that can be added.

With settings in #456 only module-level statements + type annotated objects are checked. Everything else is skipped. Here's a nice 5min video that might help: https://www.youtube.com/watch?v=Rk-Y71P_9KE

But I definitely agree with you @camilamaia that it's super important to have clear rules and to communicate them to potential contributers. There are for sure many options:
- "If you're not familiar with typing then just forget about it and write usual python code"
- "If you're familiar with typing - new type annotations are very welcome"
- "All new added code has to be type annotated" (I guess this would be too strict)
- ...?

Also I can imagine that one can add a bunch of "Good first issue" issues for adding type annotations to existing code, which could be a nice entry point for contributing.

**Comment by camilamaia** [comment]
@sleao @Stannislav thanks for the detailed answers! That makes sense to me, let's do it 💪  

I love the part of having "Good first issue" issues for adding type annotations to existing code. And we can use these examples @sleao pointed out in the docs too!

Here is the ticket for the documentation: https://github.com/scanapi/scanapi/issues/472

Thank you all!
