### ISSUE TITLE
Protected member accessed from outside the `endpoint_node's Class EndpointNode

### ISSUE THREAD

**Issue by Pradhvan** [scanapi/scanapi#434]
Accessing a protected member (a member prefixed with _) of a class from outside that class is not recommended, since the creator of that class did not intend this member to be exposed. 

We need to refactor it such that `*(child._get_requests() for child in self.child_nodes)` becomes part of the public interface of the Class EndpointNode.

Link to [code](https://github.com/scanapi/scanapi/blob/main/scanapi/tree/endpoint_node.py#L126)
```
    def _get_requests(self):
        return chain(
            (
                RequestNode(spec, self)
                for spec in self.spec.get(REQUESTS_KEY, [])
            ),
            *(child._get_requests() for child in self.child_nodes),
        )
```

**Comment by shippo16** [comment]
It's not really invoked from outside the class is it? 

child._get_requests() is being called from the initial ._get_requests() call, which makes it a recursive call.. The protected method in this case is only being called from the same protected method itself (in the same class).

Maybe you can leave it as it is..

**Comment by camilamaia** [comment]
I agree with @shippo16. +1 to ignore this issue on DeepSource. What do you think @Pradhvan ?

**Comment by camilamaia** [comment]
Issue direcly ignored on DeepSource 👍
