### ISSUE TITLE
Remove generic exception and raise a more dedicated exception that isn't very common for Class EndpointNode::run()

### ISSUE THREAD

**Issue by Pradhvan** [scanapi/scanapi#435]
The [run method ](https://github.com/scanapi/scanapi/blob/main/scanapi/tree/endpoint_node.py#L94-L94) in the Class EndpointNode's catches very generic Exception. 

We would need to be precise in catching a particular Exception so it is likely to include many unrelated errors too.

```
    def run(self):
        for request in self._get_requests():
            try:
                yield request.run()
            except Exception as e:
                error_message = f"\nError to make request `{request.full_url_path}`. \n{str(e)}\n"
                logger.error(error_message)
                session.exit_code = ExitCode.REQUEST_ERROR
                continue
```

**Comment by camilamaia** [comment]
Closed by https://github.com/scanapi/scanapi/pull/531
