### ISSUE TITLE
Re-definition found for builtin function `vars()` 

### ISSUE THREAD

**Issue by Pradhvan** [scanapi/scanapi#436]
`string_evaluator.py`, `string_evaluator.py`, `spec_evaluator.py` uses `vars` as a function argument. 

Since `vars()` is a builtin keyword. It's generally an anti-pattern to not redefine builtin function. We would need to refactor and update the definition. 

Static Analysis Issue [Link](https://deepsource.io/gh/scanapi/scanapi/issue/PYL-W0622/occurrences?page=1) to check the particular code line.

**Comment by jhermann** [comment]
Can do, question would be are those signatures part of the public API, i.e. can they be changed without complications like a deprecation shim?

**Comment by jhermann** [comment]
Also, what should the new name be, obvious candidates are `vars_` (ugly, already used at one place) and `spec_vars`.

**Comment by camilamaia** [comment]
@jfollmann you can change all occurrences of "vars" and it will not affect the final user, don't worry!

**Comment by camilamaia** [comment]
What do you think about `spec_vars`?

**Comment by Pradhvan** [comment]
+1 for `spec_vars`

**Comment by jhermann** [comment]
Final review + merge pending.
