### ISSUE TITLE
Add a pre-commit hook to check if the commit messages follow the `Conventional Commits`

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#438]
### Description the feature

As discussed [here](https://github.com/scanapi/scanapi/issues/329), it is important to have a pattern to out commit messages. But it is also annoying to check if the messages are in the pattern manually. So the idea is to automate this process using [commitlint-pre-commit-hook](https://github.com/alessandrojcm/commitlint-pre-commit-hook) or similar - as suggested by @hebertjulio.

The pre-commit hook must check if the commit message follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

### Do you have any suggestions on how to add this feature in scanapi ?

https://github.com/alessandrojcm/commitlint-pre-commit-hook

**Comment by hebertjulio** [comment]
Hey @camilamaia @Pradhvan ,

What do you think if we use [gitlint](https://jorisroovers.com/gitlint/) instead [commitlint-pre-commit-hook](https://github.com/alessandrojcm/commitlint-pre-commit-hook).

Because gitlint is write in python and it is not need install node packages to run.

**Comment by camilamaia** [comment]
@hebertjulio it works for me! It also has a way to use with pre-commit: https://jorisroovers.com/gitlint/#using-gitlint-through-pre-commit, cool 👍
