### ISSUE TITLE
Add the missing docstrings to the `code_evaluator.py` file

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#441]
Add the missing docstrings to the [code_evaluator.py](https://github.com/scanapi/scanapi/blob/main/scanapi/evaluators/code_evaluator.py) file

[Here](https://github.com/scanapi/scanapi/wiki/First-Pull-Request#7-make-your-changes) you can find instructions of how we create the [docstrings](https://www.python.org/dev/peps/pep-0257/#what-is-a-docstring).

Child of https://github.com/scanapi/scanapi/issues/411

**Comment by sijanonly** [comment]
I will be working on it.
