### ISSUE TITLE
Add the missing docstrings to the `request_node.py` file

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#445]
Add the missing docstrings to the [request_node.py](https://github.com/scanapi/scanapi/blob/main/scanapi/tree/request_node.py) file

[Here](https://github.com/scanapi/scanapi/wiki/First-Pull-Request#7-make-your-changes) you can find instructions of how we create the [docstrings](https://www.python.org/dev/peps/pep-0257/#what-is-a-docstring).

Child of https://github.com/scanapi/scanapi/issues/411

**Comment by leonardomaier** [comment]
Hi everyone, I've already created a PR resolving this issue [here](https://github.com/scanapi/scanapi/pull/522)
