### ISSUE TITLE
Fix style issue `Doc line too long FLK-W505`

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#447]
Fix `Doc line too long  FLK-W505`: https://deepsource.io/gh/scanapi/scanapi/issue/FLK-W505/occurrences

![image](https://user-images.githubusercontent.com/2728804/127705974-4b874dee-1d9d-41f9-b3ee-891a21c021f8.png)

> Docstring line lengths are recommended to be no greater than 79 characters.

Child of https://github.com/scanapi/scanapi/issues/405

**Comment by djs-djs** [comment]
I will assist with this issue--thanks!
