### ISSUE TITLE
Fix style issue `Inconsistent return statements  PYL-R1710`

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#448]
Fix style issue `Inconsistent return statements  PYL-R1710`: https://deepsource.io/gh/scanapi/scanapi/issue/PYL-R1710/occurrences

![image](https://user-images.githubusercontent.com/2728804/127706151-52032eab-34ef-4c1e-b2cc-74ec44c70678.png)

![image](https://user-images.githubusercontent.com/2728804/127706210-599bdc3c-f7fc-4078-a42a-4ab6021e2363.png)

Child of https://github.com/scanapi/scanapi/issues/405

**Comment by Agent-Hellboy** [comment]
I have some questions here as a beginner. 
https://github.com/scanapi/scanapi/blob/204e73aa17e1d5c1d7672de41c69dc3ddcdc0b19/scanapi/template_render.py#L26-L26
Is  `request.body.decode()`  is able to handle the corrupted file or is it the case that HTTPS protocol itself is able to handle it?
Do we need to check the filetype returned by header.get using the filetype module of python?

**Comment by astenstrasser** [comment]
Closed by: #532
