### ISSUE TITLE
(FLK-D200) One-line docstring should fit on one line with quotes

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#454]
## Description
If a docstring fits in a single line (72 character according to PEP8), it is recommended to have the quotes on the same line.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/scanapi/scanapi/issue/FLK-D200/occurrences/](https://deepsource.io/gh/scanapi/scanapi/issue/FLK-D200/occurrences/)

**Comment by djs-djs** [comment]
I will assist with this issue--thank you!

**Comment by Pradhvan** [comment]
Sure, go ahead @djs-djs 😄
