### ISSUE TITLE
UX / CLI: add a --browse option

### ISSUE THREAD

**Issue by jhermann** [scanapi/scanapi#465]
### Description the feature
Add a `--browse` /  `-b` option to the CLI to open the report in the browser instead of just printing where it is, to improve UX.

### Do you have any suggestions on how to add this feature in scanapi ?
Add the option, and in an `if` put a `webbrowser.open_new_tab` call below the existing logging call.

**Comment by renato04** [comment]
I'd like to do that.

**Comment by Pradhvan** [comment]
@renato04 great! Thank you 😄
