### ISSUE TITLE
Set the version on pyproject.toml automatically

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#47]
## Description

Set [the version on pyproject.toml file](https://github.com/scanapi/scanapi/blob/master/pyproject.toml#L3) automatically. We want to avoid to manually [bump the version](https://github.com/scanapi/scanapi/pull/212/files#diff-522adf759addbd3b193c74ca85243f7dR3) for each release PR.

Maybe this would be a good candidate: https://github.com/mtkennerly/poetry-dynamic-versioning. It needs more investigation

**Comment by kelvins** [comment]
I don't know exactly what the [poetry-dynamic-versioning](https://github.com/mtkennerly/poetry-dynamic-versioning) package does but there is a `version` command in the poetry itself.

For example:

```
$ poetry version prerelease
```

Another great package that works with `pyproject` is [bump2version](https://github.com/c4urself/bump2version) (a maintained fork of the [bumpversion](https://github.com/peritus/bumpversion) project).
