### ISSUE TITLE
VSCode extension for ScanAPI IntelliSense

### ISSUE THREAD

**Issue by barbosa** [scanapi/scanapi#48]
Given that ScanAPI already has a predefined yml structure, we could have a VSCode extension that autocompletes keys (`endpoints`,  `method`, `path`, etc) based on where you are in the spec tree.

This would require further investigation to see what can be achieved but the following links should give some clarity:

- https://code.visualstudio.com/api/language-extensions/overview
- https://code.visualstudio.com/api/language-extensions/programmatic-language-features

**Comment by abreumatheus** [comment]
Hi,
I just develop a initial version with completion for all tags in the specification and snippets for custom vars and python code.
If you guys approve it, we'll have to create a new repo for the extension.
You can view the code in my repo [here](https://github.com/abreumatheus/scanapi-intellisense), and download the preview release [here](https://github.com/abreumatheus/scanapi-intellisense/releases) since it's not yet published in the VSCode marketplace. 😄 

@camilamaia @barbosa

**Comment by barbosa** [comment]
@abreumatheus What a great surprise for a Sunday morning! 

![](https://media.giphy.com/media/Z9PlhqyYLGxThJd7XX/giphy.gif)

**Comment by barbosa** [comment]
@abreumatheus this looks good for a first version. Next version we can explore the other VSCode APIs. Very excited to see this progressing!

@camilamaia I can help you out if needed, creating the MS account. I had to go through the same process for Loadsmart's. Let me know.

**Comment by abreumatheus** [comment]
@barbosa All help is welcome, it was the first time i tried to develop a VSCode extension, so there's a lot to learn. 😃

**Comment by barbosa** [comment]
Very excited seeing this happening, @abreumatheus. Thank you so much for digging into their API! 💪

**Comment by camilamaia** [comment]
@abreumatheus wow, wow, wow! This is amazing 🚀 🤩 Thanks for that! I am super excited with it. Let me see to create the MS account

**Comment by abreumatheus** [comment]
@camilamaia Thanks! Don't forget the repo here on github, so i can push it there and we'll be able to start contributing 😃

**Comment by camilamaia** [comment]
@abreumatheus oh, good point! 😅 let me do it right now!

**Comment by camilamaia** [comment]
@abreumatheus https://github.com/scanapi/intellisense 😺

**Comment by camilamaia** [comment]
@abreumatheus,

@barbosa and I just created the Microsoft Account and set the token in the secrets of the new repo. This way we can automatize the deploy: https://github.com/scanapi/vscode-extension/issues/1

![image](https://user-images.githubusercontent.com/2728804/89234768-12dc7c00-d5c3-11ea-90a3-2e348761f423.png)

We also did a first release manually only for testing:

![image](https://user-images.githubusercontent.com/2728804/89234722-f50f1700-d5c2-11ea-89e7-72f75e98dce0.png)

🎉🎉🎉

**Comment by camilamaia** [comment]
I am going to close this issue because now we can starting creating specific issues in the new repo.
