### ISSUE TITLE
Fix changelog lint "Error: Resource not accessible by integration"

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#481]
### Environment
CI

### Description of the bug 

Fix changelog lint "Error: Resource not accessible by integration"

Example:

![image](https://user-images.githubusercontent.com/2728804/128019363-30771553-886b-457c-b593-b616e78e404a.png)
https://github.com/scanapi/scanapi/pull/471/checks?check_run_id=3230841936

### Expected behavior ?

Job runs successfully

### How to reproduce the the bug ?

Open a PR and run the checks in a forked repo which the owner does not belong to the ScanAPI org.

### Anthing else we need to know?

https://github.com/actions/first-interaction/issues/10

Related to #139

**Comment by Stannislav** [comment]
Reading through #139 - is there anything wrong with creating a new GitHub actions workflow that runs `diff -u <(changelog fmt -f CHANGELOG.md) CHANGELOG.md`?

**Comment by camilamaia** [comment]
@Stannislav I believe this is also an option. A good one, actually! We would just need to install the lib "directly" in the github action, since it does not have a proper github action for it now.
