### ISSUE TITLE
Add unit tests for the `__repr__` method of the EndpointNode class

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#484]
### Description

Add unit tests for the `__repr__` method of the **EndpointNode** class: https://github.com/scanapi/scanapi/blob/main/scanapi/tree/endpoint_node.py#L55

[ScanAPI Writing Tests Documentation](https://github.com/scanapi/scanapi/wiki/Writing-Tests)

**Comment by LoremIpsum42** [comment]
Hi, I have added a PR for this unit test.
