### ISSUE TITLE
Add unit tests for the `__repr__` method of the RequestNode class

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#485]
### Description

Add unit tests for the `__repr__` method of the **RequestNode** class: https://github.com/scanapi/scanapi/blob/main/scanapi/tree/request_node.py#L57

[ScanAPI Writing Tests Documentation](https://github.com/scanapi/scanapi/wiki/Writing-Tests)

**Comment by rafaquelhodev** [comment]
I've just raised a PR for this one!
