### ISSUE TITLE
Add unit tests for the `__repr__` method of the SpecEvaluator class

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#486]
### Description

Add unit tests for the `__repr__` method of the **SpecEvaluator** class: https://github.com/scanapi/scanapi/blob/main/scanapi/evaluators/spec_evaluator.py#L42

[ScanAPI Writing Tests Documentation](https://github.com/scanapi/scanapi/wiki/Writing-Tests)

**Comment by rafaquelhodev** [comment]
Hi all! I've just raised a PR for this one.
