### ISSUE TITLE
Github actions is failing due to new Python 3.6 minor release

### ISSUE THREAD

**Issue by gabrieltron** [scanapi/scanapi#511]
### Environment
- Operating System: Running in github actions
- Python version: 3.6.14

### Description of the bug 
Python 3.6.15 [was released recently](https://www.python.org/doc/versions/). setup-python supports only the latest minor version, according to [this comment](https://github.com/actions/setup-python/issues/64#issuecomment-594837888). This is causing the executions of github actions to fail.

### Expected behavior ?
Run the github actions.

### How to reproduce the the bug ?
Running a github action. In my latest PR there is a github action that failed, you can see the error message [here](https://github.com/scanapi/scanapi/pull/507/checks?check_run_id=3681947405).

### Anthing else we need to know?
Should we set the python version to 3.6.*? It seems inconvenient to bump the version after every minor release.

**Comment by Stannislav** [comment]
Seems like the culprit is this line: https://github.com/scanapi/scanapi/blob/204e73aa17e1d5c1d7672de41c69dc3ddcdc0b19/.github/workflows/lint.yml#L10

would it work to replace it by
```yaml
python-version: 3.6.x
```
?

**Comment by gabrieltron** [comment]
I think so. I'm going to assign myself to this, if that's ok, and do a little experimenting
