### ISSUE TITLE
Add hacktoberfest topic on the repository 

### ISSUE THREAD

**Issue by patrickelectric** [scanapi/scanapi#514]
It would be nice to have the topic for next month

**Comment by Pradhvan** [comment]
@patrickelectric hey 👋🏾 I am not sure we would be participating in the Hacktoberfest this year. Since there a very few maintainers and core devs who help review PR(most of them are a bit busy at the moment). 

Plus, sometimes Hacktoberfest creates more noise than actual participation from folks which is a bit overwhelming for folks who maintain it. But I would be happy to help you out if you are interested in contributing to the project in general. 😄

**Comment by JPTIZ** [comment]
> @patrickelectric hey 👋🏾 I am not sure we would be participating in the Hacktoberfest this year. Since there a very few maintainers and core devs who help review PR(most of them are a bit busy at the moment).
> 
> Plus, sometimes Hacktoberfest creates more noise than actual participation from folks which is a bit overwhelming for folks who maintain it. But I would be happy to help you out if you are interested in contributing to the project in general. smile

I understand the situation agree that depending on the team size and time it is sometimes good to refrain from participating of Hacktoberfest.

We're from a student organization that organized a schedule to participate on Hacktoberfest for a few interesting projects, and this one is one we're aiming to contribute. In that case, would adding `hacktoberfest-accepted` to specific Pull Requests be feasible?

**Comment by Pradhvan** [comment]
Hey @JPTIZ 👋🏾 

I am open to adding `hacktoberfest-accepted` labels on certain issues. Do you have any of those issues in mind that you or folks participating would be interested in ? 

Though seeing the problems I mentioned I am not sure how much mentorship I can provide in tackling those issues. But if you have certain pre-decided issues that folks can independently work on or something like and `good-first-issue` I can happily tag them with `hacktoberfest-accepted`. Just comment on the issue and it would be done.

**Comment by JPTIZ** [comment]
@Pradhvan Hello! Thanks for the response! No need to say sorry, we have an entire month :)

Taking a quick look at the issues, I find some quite interesting for us to work on (e.g. #501 and #472). We might discuss here internally, but I think there's room for us to first analyse (the issues are explained very clearly, so we could comment when we do not fully understand one that seems very good to contribute to).

**Comment by Pradhvan** [comment]
@JPTIZ I would say #501 would be a good starting point. For the whole adding types to the project and documentation towards it, I would say to wait a bit and maybe pick that up later.  So maybe you #452 can be a swap for that. 😄

**Comment by Pradhvan** [comment]
Closing this issue now. We can plan better for the next hacktoberfest.
