### ISSUE TITLE
Fix typos in ```spec_evaluator.py```

### ISSUE THREAD

**Issue by leonardomaier** [scanapi/scanapi#525]
File: [spec_evaluator.py](https://github.com/scanapi/scanapi/blob/main/scanapi/evaluators/spec_evaluator.py#L72)

```Python
    @classmethod
    def filter_response_var(cls, spec_vars):
        """Returns a copy pf ``spec_vars`` without 'response' references.
        Any items with a ``response.*`` reference in their value are left out.
        Returns:
            [dict]: filtered dictionary.
        """
        pattern = re.compile(r"(?:(\s*response\.\w+))")
        return {k: v for k, v in spec_vars.items() if not pattern.search(v)}
```

Update docstring typo in the classmethod `Returns a copy pf` -> `Returns a copy of`

**Comment by Pradhvan** [comment]
@leonardomaier thank you for opening the issue. I just updated the issue. I hope you don't mind. 😄

**Comment by leonardomaier** [comment]
> @leonardomaier thank you for opening the issue. I just updated the issue. I hope you don't mind. 😄

No problem, it looks a way better, I'm gonna update another issue I've create to follow this pattern 😄

**Comment by leonardomaier** [comment]
Done in #527 😉
