### ISSUE TITLE
There are some option to set verify=False to requests?

### ISSUE THREAD

**Issue by samueltcsantos** [scanapi/scanapi#529]
### Environment
- Operating System: Linux Xubuntu 16.04
- Python version: 3.6

### What you intend to do with scanapi ?
A  want make a request to web server running locally with HTTPS enabled, but I need some way to make requests dont verify SSL.

I need something like that?
requests.post(url='https://example.com', data={'bar':'baz'}, verify=False)

### Expected behavior ?

There are some option for me reach that, saying to requests include 'verify=False'?

I'm trying to avoid this error:

Error to make request `https://127.0.0.1:443/auth/authenticate`. 
HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /auth/authenticate (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))

Thanks in advance!

---

scanapi has a [discord server](https://discord.gg/f3cCXJ2ZPB) so feel free to join and say 👋 hello. Maybe share the issue link?

**Comment by camilamaia** [comment]
Hey, @samueltcsantos, thanks for the question! Currently, this is not possible. But it makes total sense to have it indeed.

**Comment by uesleicarvalhoo** [comment]
Hi @camilamaia, if you want, i like to implement this feature, i will open a pull request coming soon :)

**Comment by Pradhvan-at-STG** [comment]
@uesleicarvalhoo thank you for taking this one. Assigned it you. 😄

**Comment by astenstrasser** [comment]
Hi @uesleicarvalhoo, sure you can take it!
Me and @camilamaia were thinking about implementing it in a generic way, so similar options could be also used. 
@camilamaia, any suggestions?

**Comment by uesleicarvalhoo** [comment]
Maybe something with it, where options accept all request.session key words?

```ymal
endpoints:
  - name: pokeapi
    path: https://localhost:8000/
    verify_tls: false
    endpoints:
      - name: health check
        path: health-check
        requests:
          - name: check if application is alive
            method: get
            options:
              - verify: false
              - timeout: 10
            tests:
              - name: status_code_is_200
                assert: ${{ response.status_code == 200 }}
              - name: response_time_is_under_half_second
                assert: ${{ response.elapsed.total_seconds() < 0.5 }}

```

**Comment by camilamaia** [comment]
@uesleicarvalhoo yeah, we were thinking on something in the exactly way you suggested. With this approach we can accommodate other parameters from requests too!

**Comment by Pradhvan** [comment]
@uesleicarvalhoo replied on the PR. 😄

**Comment by uesleicarvalhoo** [comment]
Thanks @Pradhvan, fixed!

**Comment by samueltcsantos** [comment]
Thanks you so much. It's a great tool.

Em sex., 8 de jul. de 2022 05:49, Camila Maia ***@***.***>
escreveu:
