### ISSUE TITLE
Add rich for summary in the console

### ISSUE THREAD

**Issue by astenstrasser** [scanapi/scanapi#538]
## Feature request

* Add test summary in console with [rich](https://github.com/Textualize/rich)

### Description of the feature

As discussed here: https://github.com/scanapi/scanapi/pull/518

**Comment by Pradhvan** [comment]
@astenstrasser I can take this up if anyone else is not working on this. 😄

**Comment by astenstrasser** [comment]
> @astenstrasser I can take this up if anyone else is not working on this. 😄

Hi @Pradhvan! 
Thanks! I actually forgot to assign myself, but I already started working on this.
Should open the PR soon :)

**Comment by Pradhvan** [comment]
@astenstrasser ah! okay. Thank You 😄 

Looking forward to the PR. 🙌🏾
