### ISSUE TITLE
Update dependencies to current versions

### ISSUE THREAD

**Issue by robinmackaij** [scanapi/scanapi#546]
## Feature request
The current dependencies are locked to older versions of e.g. PYYAML (6.0) and jinja2 (3.1.x). This makes scanapi incompatible with other tools in the API eco-system or API implementations. This makes it impossible to use scanapi as dev dependency.

### Description the feature
Update the dependencies to include latest major versions of the dependencies.

### Is your feature request related to a problem?
Yes, I cannot add scanapi to some of my projects due to conflicting dependencies.

**Comment by camilamaia** [comment]
Thanks for the report @robinmackaij 

This is super important, we need to tackle it ASAP. @astenstrasser and I did some tests and it seems we will need to stop giving support to python 3.6 in order to achieve it. I am ok with it, since 3.6 is quite old now.

**Comment by Pradhvan** [comment]
Thank You @robinmackaij 👏🏾

**Comment by camilamaia** [comment]
@robinmackaij the version with the upgrades is already live! Download the latest ScanAPI version (2.7.0) to use it :)
