### ISSUE TITLE
Generate automated documentation from docstrings

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#62]
Generate automated code documentation from the [docstrings](https://www.datacamp.com/community/tutorials/docstrings-python).

https://wiki.python.org/moin/DocumentationTools
https://www.sphinx-doc.org/en/master/

**Comment by 5pence** [comment]
Going to have a crack at this :)

**Comment by 5pence** [comment]
Writing up some docstring I cam across this:
`    def start(self):
        """ Start session method that sets the time this Session object began. """
        self.started_at = datetime.now()`

Why bother having this? wouldn't it be better to have `self.started_at = datetime.now()` inside the constructor __init__ ?

**Comment by camilamaia** [comment]
Closed by #230
