### ISSUE TITLE
Alert if CHANGELOG.md was not updated

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#94]
## Description

When a PR is opened and the CHANGELOG.md was not modified, send an alert to remember to update it.

Possible to be implemented with:
- [Danger](https://github.com/danger/danger)
- [Peril](https://github.com/danger/peril)

Or, alternatively, to create a CircleCI check that fails when it is not updated.

**Comment by barbosa** [comment]
https://github.com/marketplace/actions/changelog-reminder
